add file 017
Katekarri/lernJs pull request #4
Opened 2022-03-13 06:40 UTC by Katekarri

решила несколько задач

2022-03-16 07:29 UTC, Katekarri commented
![Screenshot_3](https://user-images.githubusercontent.com/90210173/158538477-61a32802-d8d3-4a93-80d7-ed122c2a6855.png)

2022-03-21 12:12 UTC, Katekarri commented
![Screenshot_1](https://user-images.githubusercontent.com/90210173/159258472-3f33efdd-25f9-4273-891c-e09730cab702.png)
надо разораться с этой задачей

2022-03-21 12:51 UTC, mikalai-hryb requested changes

2022-03-21 12:51 UTC, mikalai-hryb commented on 017.js
> +console.log(example8);
я и сам сразу не заметил, но тут походу `-` это тире, а не знак минус
можешь не исправлять, просто глаз зацепился

2022-03-21 12:51 UTC, mikalai-hryb commented on 017.js
> +console.log(example);
хорошо что ты нашла такое решение, но для этой задачи не нужно использовать `for of` 
попробуй запустить этот код с таким массивом `[8, 6, 9, 4, 35]`, думаю результат получится неожиданным для тебя

2022-03-21 12:51 UTC, mikalai-hryb commented on 042.js
> +    alert(i);
с решением всё хорошо, но ожидается `console.log` вместо `alert`

2022-03-21 12:51 UTC, mikalai-hryb commented on 042.js
> +    alert(i);
с решением всё хорошо, но ожидается `console.log` вместо `alert`

2022-03-21 12:51 UTC, mikalai-hryb commented on 045.js
> +}
да, всё отлично! ❤️

2022-03-21 12:51 UTC, mikalai-hryb commented on tasks.js
> +
ты сама создала массив с 10 `x` и просто выводишь эти `x`
а нужно массив заполнить 10 `x`, т.е у тебя должен быть пустой массив изначально, потом ты запускаешь `for` который и заполнит массив
и не просят что-то выводить

2022-03-21 12:51 UTC, mikalai-hryb commented on tasks.js
> +}
читай предыдущий коммент

2022-03-21 12:51 UTC, mikalai-hryb commented on tasks.js
> +}
массив должен быть с произвольными числами, например, [10, 51, 7, 8, -15, -145, 1]
и с помощью цикла должно быть выведено:
7
8
1

2022-03-21 12:51 UTC, mikalai-hryb commented on tasks.js
> +}
код очень близок к правильному
1. он не работает, так как есть описка
2. не просят что-то выводить кроме `Есть`

2022-03-21 12:51 UTC, mikalai-hryb commented on tasks.js
> +console.log(sum);
`console.log` нужно использовать там где его требует
если он используется для самопроверки, то в конечной результате его не должно быть в коде
решение правильное

2022-03-21 12:51 UTC, mikalai-hryb commented on tasks.js
> +console.log(sum7 / example7[i]);//????????
как определяется количество элементов в массиве?

2022-03-22 06:08 UTC, Katekarri commented on 017.js
> +console.log(example);
![Screenshot_2](https://user-images.githubusercontent.com/90210173/159418439-987f9b6a-b641-40e6-b903-20f0e9adb542.png)

2022-03-22 19:51 UTC, mikalai-hryb commented on tasks.js
> +}
массив example2 будет пустым после цикла

2022-03-23 06:18 UTC, Katekarri commented on 017.js
> +console.log(example);
сделала

2022-03-23 06:19 UTC, Katekarri commented on 042.js
> +    alert(i);
готово

2022-03-23 06:19 UTC, Katekarri commented on 042.js
> +    alert(i);
готово

2022-03-23 06:20 UTC, Katekarri commented on 045.js
> +}
ура!

2022-03-23 06:20 UTC, Katekarri commented on tasks.js
> +
исправила

2022-03-23 06:20 UTC, Katekarri commented on tasks.js
> +}
исправила

2022-03-23 06:22 UTC, Katekarri commented on tasks.js
> +console.log(sum7 / example7[i]);//????????
исправила во время звонка

2022-03-23 06:24 UTC, Katekarri commented on tasks.js
> +}
![Screenshot_3](https://user-images.githubusercontent.com/90210173/159636557-4ad75bd5-0a77-498d-969c-df77afc8d07e.png)

2022-03-23 06:26 UTC, Katekarri commented on tasks.js
> +console.log(sum);
закомментировала)

2022-03-24 20:51 UTC, Katekarri commented
> ![Screenshot_3](https://user-images.githubusercontent.com/90210173/158538477-61a32802-d8d3-4a93-80d7-ed122c2a6855.png)

test

2022-03-26 05:50 UTC, Katekarri commented
test

2022-03-26 05:50 UTC, merged