add file cycles
Katekarri/lernJs pull request #7
Opened 2022-04-12 19:33 UTC by Katekarri

2022-04-13 15:25 UTC, mikalai-hryb commented on function.js
> +// Используя оператор ?(тут наверное ошибка имеется в виду ??)
ошибки нету
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Conditional_Operator

2022-04-13 15:26 UTC, mikalai-hryb commented on function.js
> +  }
попробуй использовать вместо 5 этих строк 1 строку
это можно сделать с помощью тернарного оператора

2022-04-15 14:57 UTC, mikalai-hryb requested changes

2022-04-15 14:57 UTC, mikalai-hryb commented on cycles.js
> +}
решение не работает
что будет если пользователь введет число меньше 100?
ты попадаешь в беспонечный цикл и комп в конечном итоге зависнет так как этот цикл "съест" всю оперативную память

2022-04-15 14:57 UTC, mikalai-hryb commented on function.js
> +  }
решение с тернарным оператором ниже верное, а это решение не верное, я упустил, тут должно быть `a < b`

2022-04-15 14:57 UTC, mikalai-hryb commented on function.js
> +}
решение верное
предоставть ещё одно решение в одну строку (без цикла)

2022-04-15 14:57 UTC, mikalai-hryb commented on function.js
> +);
всё верно

2022-04-16 11:21 UTC, mikalai-hryb commented on 110.js
> +	alert(num * num *num);
Используй оператор возведения в степень

2022-04-16 11:21 UTC, mikalai-hryb commented on 110.js
> +  return num;
Зачем в этой функции return?
Название функции не говорящее, переименуй
Что будет если ввести 0? Получится ожидаемый результат?

2022-04-16 11:21 UTC, mikalai-hryb commented on 110.js
> +}
Название функции непонятное

2022-04-16 11:21 UTC, mikalai-hryb commented on function.js
> +let pow2 = (x, n) => x * n;
Эта функция разве рабочая?

2022-04-20 09:24 UTC, mikalai-hryb commented on 111.js
> +}
корень вычисляется иначе

2022-04-20 09:29 UTC, mikalai-hryb commented on 111.js
> +}
перешиши также в стрелочную функцию

2022-04-20 09:31 UTC, mikalai-hryb commented on cycles.js
> +    //null это когда пользователь нажал отмена или esc
с числом меньше 100 код не работает

2022-04-20 09:32 UTC, mikalai-hryb commented on cycles.js
> +}
не работает

2022-04-20 09:34 UTC, mikalai-hryb reviewed
много функций прорешено, это хорошо

2022-04-21 14:24 UTC, Katekarri commented on 111.js
> +}
готово

2022-04-21 14:25 UTC, Katekarri commented on cycles.js
> +}
переделала, часть решения найдено готовым ,попробовала объяснить , но нужны твои пояснения

2022-04-21 15:48 UTC, mikalai-hryb commented on 111.js
> +	return Math.sqrt();
разве функция calculateSquareRoot работает правильно?

2022-04-21 15:48 UTC, mikalai-hryb commented on 111.js
> +let func6 = (num1, num2) => (num1 > 0 && num2 > 0) ? num1 *= num2 : num1 -= num2;
нужно будет поговорить об этом

2022-04-21 15:57 UTC, mikalai-hryb commented on cycles.js
> +  //а значит оно простое  мы выводим его в консоль, и переходим к следующему числу
надеюсь ты разобралась

2022-04-21 16:49 UTC, mikalai-hryb commented on 111.js
> +}
хорошо, поговорим

2022-04-21 16:50 UTC, mikalai-hryb commented on cycles.js
> +}
хорошо, поговорим

2022-04-21 19:02 UTC, Katekarri commented
> много функций прорешено, это хорошо

ok

2022-04-21 19:11 UTC, merged