22.04.22
Katekarri/lernJs pull request #8
Opened 2022-04-24 16:43 UTC by Katekarri

только что  вспомнила что не создала pull request...все ждала твоих комментариев

2022-04-25 18:42 UTC, mikalai-hryb requested changes

2022-04-25 18:42 UTC, mikalai-hryb commented on 112.js
> +}
1. вычисляй квадрат числа с помощью оператора возведения в ступень
2. эта функция работает неправино
если я сделаю 
```
const r = squareSum([3,4,5])
console.log(r)
```
ожидаю увидеть 50, тут этого не произойдет

2022-04-25 18:42 UTC, mikalai-hryb commented on funcNewLevel.js
> +}
функция возвращает результат выполнения функции console.log(), т.е underfined, а должна время года

2022-04-25 18:42 UTC, mikalai-hryb commented on funcNewLevel.js
> +}
решение неполное
https://docs.microsoft.com/ru-ru/office/troubleshoot/excel/determine-a-leap-year#more-information

2022-04-25 18:42 UTC, mikalai-hryb commented on funcNewLevel.js
> +}
запусти такой код
```
const x = sum_range(3, 1)
const y = sum_range(1, 5)
```
чему будет равен `y`? а должен?

2022-04-25 18:42 UTC, mikalai-hryb commented on funcNewLevel.js
> +}
получаемая строка не соответствует условию

2022-04-25 18:51 UTC, Katekarri commented on funcNewLevel.js
> +}
название по условиям задачи :   Написать функцию is_year_leap, принимающую 1 аргумент — год, и возвращающую True, если год високосный, и False иначе

2022-04-25 18:54 UTC, mikalai-hryb commented on funcNewLevel.js
> +}
понял, мой косяк, 2 пунк не принимай во внимание

2022-04-25 18:55 UTC, mikalai-hryb commented on funcNewLevel.js
> +}
2 пунк не принимай во внимание

2022-04-25 18:55 UTC, Katekarri commented on funcNewLevel.js
> +}
function rgb(a = 0, b = 0, c = 0) {
  return `rgb(${a}, ${b}, ${c})`;
}
// rgb(4, 67);

2022-04-25 18:57 UTC, Katekarri commented on funcNewLevel.js
> +}
биктики не перенеслись((

2022-04-25 18:58 UTC, Katekarri commented on funcNewLevel.js
> +}
название функции по условиям задачи : Написать функцию season, принимающую 1 аргумент — номер месяца (от 1 до 12), и возвращающую время года, которому этот месяц принадлежит (зима, весна, лето или осень).

2022-04-25 19:21 UTC, Katekarri commented on 112.js
> +}
если честно не понятно ... по условиям 2 числа ....

2022-04-25 19:23 UTC, mikalai-hryb commented on 112.js
> +}
в смысле 2 числа?
что именно непонятно?

2022-04-27 09:31 UTC, mikalai-hryb commented on 112.js
> +    x += y; //увеличиваем переменную х
1. for..of тут лучше подходит
2. 7-9 строки можно заменить одной строкой

2022-04-27 09:31 UTC, mikalai-hryb commented on 112.js
> +    let arr = [start, end];
нужна ли создавать этот массив?

2022-04-27 09:31 UTC, mikalai-hryb commented on 112.js
> +    let arr = [start, end];
нужна ли создавать этот массив?
на выходе нужно заполнить массив , все по условием заполняется

2022-04-27 21:04 UTC, mikalai-hryb commented on funcNewLevel.js
> +}
откуда 365 и 366?

функция работает неправильно, она не покрывает следующие случаи
```
По этой причине следующие годы не являются високосными:
1700, 1800, 1900, 2100, 2200, 2300, 2500, 2600
Это потому, что они делятся без остатка на 100, но не на 400.

Следующие годы – високосные: 1600, 2000, 2400
Это потому, что они делятся без остатка на 100 и 400.
```

2022-04-28 19:24 UTC, mikalai-hryb commented on 112.js
> +console.log(funk(5))
избавиться от `arr`

2022-04-28 19:25 UTC, mikalai-hryb commented on 112.js
> +    let arr = [start, end];
избавиться от `arr`

2022-04-28 19:26 UTC, mikalai-hryb commented on funcNewLevel.js
> +}
переписать через `['зима','весна','лето','осень']`

2022-04-28 19:26 UTC, mikalai-hryb commented on funcNewLevel.js
> +}
удалить за ненадобностью

2022-04-28 19:26 UTC, mikalai-hryb commented on funcNewLevel.js
> +}
не все случаи функция покрывает

2022-04-28 19:28 UTC, mikalai-hryb commented on funcNewLevel.js
> +}
избавиться от `arr`

2022-05-03 18:08 UTC, mikalai-hryb requested changes

2022-05-03 18:08 UTC, mikalai-hryb commented on 039.js
> +// Задача 1
объекты это уже другая тема
они должны быть в другом ПРе

2022-05-03 18:08 UTC, mikalai-hryb commented on 039.js
> +console.log(obj1)
почему ты тут используешь `let`?
ты ведь не будешь изменять эту переменную, а значит тут должно быть `const`
это относится ко всем задачам
https://learn.javascript.ru/let-const

2022-05-03 18:08 UTC, mikalai-hryb commented on 039.js
> +let sumElement = (obj2['a'] + obj2['b'] + obj2['c']);
зачем тут скобки?

2022-05-03 18:08 UTC, mikalai-hryb commented on 039.js
> +console.log(user.nameUser + user.surname + user.patronymic);
твоё имя или фамилия содержит пробел?
думаю нет, тогда почему ты добавляешь пробел к `nameUser` и `surname`?

2022-05-03 18:08 UTC, mikalai-hryb commented on 039.js
> +let today = date.year + '-' + date.month + '-' + date.day;
используй или шаблонные строки или `.join()` для отображения в нужном формате

2022-05-03 18:08 UTC, mikalai-hryb commented on funcNewLevel.js
> +testMe(calculateDeposit, 127, 3, 50, 169.04)
задачу нужно дорешать

2022-05-04 09:08 UTC, mikalai-hryb commented on 113.js
> +// Задача 1
в файле 3 функции, используй testMe для проверки работы функций

2022-05-04 09:11 UTC, mikalai-hryb commented on 113.js
> +// Задача 1
соблюдай оформление кода
https://learn.javascript.ru/coding-style

2022-05-04 09:14 UTC, mikalai-hryb commented on 113.js
> +checkNum([2,7,6,8,12,16])
в условии задачи не просят возвращать массив с нечетными числами

2022-05-04 19:38 UTC, merged